# Generated by Django 5.2.14 on 2026-05-26 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#768970', max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a 7-character hex value, e.g. '#768970'.", regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#d4af37', max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a 7-character hex value, e.g. '#768970'.", regex='^#[0-9A-Fa-f]{6}$')])),
                ('surface_color', models.CharField(default='#f9f7f2', max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a 7-character hex value, e.g. '#768970'.", regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#2d2926', max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a 7-character hex value, e.g. '#768970'.", regex='^#[0-9A-Fa-f]{6}$')])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Hero title — e.g. 'Evelyn & James' or 'Rodolfo's 30th'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('starts_at', models.DateTimeField()),
                ('template_choice', models.CharField(choices=[('minimal', 'Modern Minimal'), ('classic', 'Classic Elegance'), ('floral', 'Romantic Floral')], default='minimal', max_length=16)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Italic intro under the hero title.', max_length=300)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('details_body', models.TextField(blank=True, help_text='Single block of details copy (Modern Minimal template).')),
                ('our_story', models.TextField(blank=True)),
                ('ceremony_time', models.CharField(blank=True, max_length=200)),
                ('ceremony_venue', models.CharField(blank=True, max_length=200)),
                ('ceremony_address', models.CharField(blank=True, max_length=300)),
                ('reception_time', models.CharField(blank=True, max_length=200)),
                ('reception_venue', models.CharField(blank=True, max_length=200)),
                ('reception_address', models.CharField(blank=True, max_length=300)),
                ('lodging_info', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='invitations.palette')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="A name to recognize the recipient(s), e.g. 'The Smiths'.", max_length=200)),
                ('num_guests', models.PositiveSmallIntegerField(default=1, help_text='How many people this invitation is for.')),
                ('message', models.TextField(blank=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='invitations.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=8)),
                ('message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
            },
        ),
    ]
