# Generated by Django 5.2.14 on 2026-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='Language used for chrome text on the public invitation page.', max_length=8),
        ),
    ]
