# Generated by Django 5.2.14 on 2026-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='details_image_url',
            field=models.URLField(blank=True, help_text='Side photo in the details block (Modern Minimal).', max_length=500),
        ),
        migrations.AddField(
            model_name='party',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Top-of-page hero photo. Paste any public image URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='party',
            name='our_story_image_url',
            field=models.URLField(blank=True, help_text="Photo alongside the 'Our Story' section.", max_length=500),
        ),
    ]
