# Generated by Django 5.2.14 on 2026-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_party_details_image_url_party_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='template_choice',
            field=models.CharField(choices=[('minimal', 'Modern Minimal'), ('classic', 'Classic Elegance'), ('floral', 'Romantic Floral'), ('midnight_minimal', 'Midnight Minimal'), ('midnight_elegance', 'Midnight Elegance'), ('midnight_floral', 'Midnight Floral')], default='minimal', max_length=32),
        ),
    ]
