# Generated by Django 5.2.14 on 2026-05-26 18:19
#
# Hand-edited from `makemigrations` output to insert a data-migration step
# (`copy_columns_to_json`) that preserves existing template-customizable
# content when the per-field columns are dropped into the new
# `theme_content` JSONField.

from django.db import migrations, models


# Fields on Party (pre-migration) whose data should be merged into the
# new `theme_content` JSONField before the columns are dropped.
_FIELDS_TO_COPY: tuple[str, ...] = (
    "hero_subtitle",
    "rsvp_deadline",
    "details_body",
    "our_story",
    "ceremony_time",
    "ceremony_venue",
    "ceremony_address",
    "reception_time",
    "reception_venue",
    "reception_address",
    "lodging_info",
    "hero_image_url",
    "our_story_image_url",
    "details_image_url",
)


def copy_columns_to_json(apps, schema_editor):
    """Move per-column theme content into Party.theme_content (dict)."""
    Party = apps.get_model("invitations", "Party")
    for party in Party.objects.all():
        content: dict = dict(party.theme_content or {})
        for field in _FIELDS_TO_COPY:
            value = getattr(party, field, None)
            if value in (None, ""):
                continue
            # Dates serialize to ISO strings for JSON storage; the live
            # model's `content_for_display()` parses them back at render time.
            if hasattr(value, "isoformat"):
                content[field] = value.isoformat()
            else:
                content[field] = value
        if content:
            party.theme_content = content
            party.save(update_fields=["theme_content"])


def noop_reverse(apps, schema_editor):
    # Reversing this migration would lose any data added under the new schema
    # (new template fields don't have columns to map back to). No-op so the
    # reverse path doesn't silently delete data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_party_template_choice'),
    ]

    operations = [
        # 1) Add the new JSONField (default={} so existing rows get an empty dict).
        migrations.AddField(
            model_name='party',
            name='theme_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        # 2) Copy existing column values into the JSON dict (still readable here).
        migrations.RunPython(copy_columns_to_json, noop_reverse),
        # 3) Drop the now-redundant columns.
        migrations.RemoveField(model_name='party', name='ceremony_address'),
        migrations.RemoveField(model_name='party', name='ceremony_time'),
        migrations.RemoveField(model_name='party', name='ceremony_venue'),
        migrations.RemoveField(model_name='party', name='details_body'),
        migrations.RemoveField(model_name='party', name='details_image_url'),
        migrations.RemoveField(model_name='party', name='hero_image_url'),
        migrations.RemoveField(model_name='party', name='hero_subtitle'),
        migrations.RemoveField(model_name='party', name='lodging_info'),
        migrations.RemoveField(model_name='party', name='our_story'),
        migrations.RemoveField(model_name='party', name='our_story_image_url'),
        migrations.RemoveField(model_name='party', name='reception_address'),
        migrations.RemoveField(model_name='party', name='reception_time'),
        migrations.RemoveField(model_name='party', name='reception_venue'),
        migrations.RemoveField(model_name='party', name='rsvp_deadline'),
    ]
