# Generated by Django 5.2.14 on 2026-07-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_remove_party_ceremony_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='template_choice',
            field=models.CharField(choices=[('minimal', 'Modern Minimal'), ('classic', 'Classic Elegance'), ('floral', 'Romantic Floral'), ('midnight_minimal', 'Midnight Minimal'), ('midnight_elegance', 'Midnight Elegance'), ('midnight_floral', 'Midnight Floral'), ('secret_garden', 'Secret Garden')], default='minimal', max_length=32),
        ),
    ]
