# Generated by Django 5.2.14 on 2026-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_alter_party_template_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='template_choice',
            field=models.CharField(choices=[('minimal', 'Modern Minimal'), ('classic', 'Classic Elegance'), ('floral', 'Romantic Floral'), ('midnight_minimal', 'Midnight Minimal'), ('midnight_elegance', 'Midnight Elegance'), ('midnight_floral', 'Midnight Floral'), ('secret_garden', 'Secret Garden'), ('wildflower_wreath', 'Wildflower Wreath')], default='minimal', max_length=32),
        ),
    ]
